name: AdminPrivateChat
main: com.ammaraskar.adminonly.AdminChat
version: 2.0
author: ammaraskar
description: >
             Talk with other admins privately
commands:
  amsg:
    description: Talk with other admins privately
    usage: |
            /amsg message
  a:
    description: Alias for amsg, can be enabled from config
    usage: |
            /a message
  atoggle:
    description: Toggle admin only chat
    usage: |
            /atoggle 
permissions:
  adminchat.send:
    default: false
    description: allows player to send out message with /a or /amsg
  adminchat.recieve:
    default: false
    description: allows player to recieve messages sent with /a or /amsg
  adminchat.toggle:
    default: false
    description: allows player to toggle sending to all admins on and off